name: CD Pipeline

on:
  push:
    branches:
      - n2h-deployment-2

jobs:
  push-question-service-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/question-service'

    steps:
      - name: Checkout Question Service directory
        uses: actions/checkout@v4
    
      - name: create .env file for Question Service
        run: |
          touch .env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
          echo PORT=${{ secrets.QUESTION_SERVICE_PORT }} >> .env

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: build, tag, push Question Service image to Dockerhub
        working-directory: backend/question-service
        run: |
          docker build -t g46-question-service .
          docker tag g46-question-service ${{ secrets.DOCKERHUB_USERNAME }}/g46-question-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/g46-question-service